services:
  - type: web
    plan: free 
    name: ecclesiaops-backend
    runtime: node
    repo: https://github.com/JOscarSoft/EcclesiaOps
    branch: master
    rootDir: backend
    buildCommand: npm install --include=dev && npm run build
    startCommand: node dist/main
    envVars:
      - key: NODE_ENV
        value: production
      - key: MONGODB_URI
        sync: false
      - key: JWT_SECRET
        sync: false

  - type: web
    plan: free 
    name: ecclesiaops-frontend
    runtime: node
    repo: https://github.com/JOscarSoft/EcclesiaOps
    branch: master
    rootDir: frontend
    buildCommand: npm install --include=dev && npm run build
    startCommand: npx serve -s dist -l 3000
    envVars:
      - key: VITE_API_URL
        value: https://ecclesiaops-backend.onrender.com/api
